version: '3.7'
services:
  chromadb:
    image: chromadb/chromadb:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_HOST=0.0.0.0
      - CHROMADB_PORT=8000
    volumes:
      - chromadb_data:/data

volumes:
  chromadb_data: