### Simple chat completion
GET http://localhost:9090/api/chat?prompt=tell me a joke about java programmer

// GPT-4o :: "output": "Why do Java programmers wear glasses?\n\nBecause they don't C#!"
// Claude :: "output": "Sure, here's a joke about Java programmers:\n\nWhy did the Java programmer quit their job?\nThey didn't get arrays!"
// Gemini PRO :: "output": "A Java programmer is asked, \"If a plane is flying in the sky with 5 people and 1 guy jumps off, what is my name?\"\nThe Java programmer replies, \"What is your name?\"\n\"John,\" said the person asking.\nThe Java programmer then says, \"Then your name is John.\"\n"

<> 2024-11-21T142911.200.json

### Chat history test before
GET http://localhost:9090/api/chat?prompt=I have 5 USD in my pocket

### Chat history test after
GET http://localhost:9090/api/chat?prompt=how many USD I have in my pocket?

### Time plugin invocation
GET http://localhost:9090/api/chat?prompt=what is the current time in New York?
//"output": "The current time in New York is 12:29:06 PM."

### Lights plugin invocation
GET http://localhost:9090/api/chat?prompt=turn on the light 1
//"output": "Okay, I've turned on light 1. Is there anything else?"

### Similarity search
GET http://localhost:9090/api/chat/search?
    query=monoidal preordering
    &topK=3
